package com.domatapp.buildlogic

import com.android.build.api.dsl.KotlinMultiplatformAndroidLibraryExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.api.plugins.ExtensionAware
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

/**
 * Opts a KMP library module into unit tests: `commonTest` with kotlin-test and
 * kotlinx-coroutines-test, run on the Android host (JVM) and, on macOS, the iOS simulator.
 *
 * A separate plugin rather than part of `domatapp.kmp.library` on purpose. The
 * com.android.kotlin.multiplatform.library plugin keeps host tests off by default, and
 * `withHostTest { }` eagerly creates the test variant and compilation - Android's own guidance is
 * not to call it from a convention every module applies. Applying this plugin *is* the opt-in; today
 * that is every `feature:*:presentation` module (ViewModel tests generated by the ui-test-verify
 * skill), and nothing else.
 */
class TestConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) = with(target) {
        pluginManager.withPlugin(ANDROID_KMP_LIBRARY_PLUGIN_ID) {
            val libs = extensions.getByType(VersionCatalogsExtension::class.java).named("libs")
            extensions.configure<KotlinMultiplatformExtension> {
                (this as ExtensionAware).extensions.configure(KotlinMultiplatformAndroidLibraryExtension::class.java) {
                    withHostTest { }
                }
                sourceSets {
                    commonTest {
                        dependencies {
                            implementation(libs.findLibrary("test-kotlin").get())
                            implementation(libs.findLibrary("test-coroutines").get())
                        }
                    }
                }
            }
        }
    }

    companion object {
        // Applied by domatapp.kmp.library together with (and after) org.jetbrains.kotlin.multiplatform;
        // waiting for it guarantees both the Kotlin and the Android extensions exist.
        const val ANDROID_KMP_LIBRARY_PLUGIN_ID = "com.android.kotlin.multiplatform.library"
    }
}
