package com.domatapp.shared.app

import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Snackbar
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import com.domatapp.core.design.theme.DomatTheme
import com.domatapp.core.navigation.OnboardingGraph
import com.domatapp.core.navigation.gezginJson
import com.domatapp.core.navigation.gezginTopology
import com.domatapp.core.presentation.compose.LocalSnackbarHostState
import com.domatapp.feature.auth.presentation.navigation.authGraphEntries
import com.domatapp.feature.home.presentation.navigation.mainGraphEntries
import com.domatapp.feature.onboarding.presentation.navigation.onboardingGraphEntries
import dev.gezgin.core.compose.GezginDisplay
import dev.gezgin.core.compose.rememberNavigator

/**
 * The whole application, shared by both platforms.
 *
 * Only the host differs: `MainActivity` on Android and the `ComposeUIViewController` that
 * `MainViewController()` builds on iOS. This used to live in `composeApp` and be Android-only,
 * because Gezgin had no iOS klib and the graph could not leave `androidMain`; it now does, so the
 * navigator, the entry bundles and every screen they register are compiled once.
 *
 * @param onRootBack what a back gesture at the bottom of the stack means. Android finishes the
 *   Activity; iOS passes an empty lambda, because Apple forbids an app from terminating itself and
 *   Gezgin's `platformDefaultRootBack()` is a no-op there for the same reason.
 */
@Composable
fun DomatApp(onRootBack: () -> Unit) {
    val snackbarHostState = remember { SnackbarHostState() }

    // `gezginTopology` and `gezginJson` are generated by Gezgin into :core:navigation, next to the
    // graph they describe. On Android the navigator is held in an Activity-scoped holder, so it
    // survives configuration change; on both platforms its serialized snapshot is restored under
    // `restoreKey`.
    val navigator = rememberNavigator(
        start = OnboardingGraph.OnboardingWelcomeRoute,
        topology = gezginTopology,
        json = gezginJson,
        restoreKey = "domat-root",
        onRootBack = onRootBack,
    )

    DomatTheme {
        CompositionLocalProvider(LocalSnackbarHostState provides snackbarHostState) {
            Scaffold(
                snackbarHost = {
                    SnackbarHost(hostState = snackbarHostState) { data ->
                        Snackbar(
                            snackbarData = data,
                            containerColor = MaterialTheme.colorScheme.errorContainer,
                            contentColor = MaterialTheme.colorScheme.onErrorContainer,
                        )
                    }
                }
            ) { innerPadding ->
                // The entries lambda is captured once, on first composition - every register call
                // in it must be unconditional.
                GezginDisplay(
                    navigator = navigator,
                    modifier = Modifier.padding(innerPadding),
                    transitions = DomatNavTransitions,
                ) {
                    onboardingGraphEntries()
                    authGraphEntries()
                    mainGraphEntries()
                }
            }
        }
    }
}
