plugins {
    alias(libs.plugins.domatapp.kmp.library)
    alias(libs.plugins.domatapp.kmp.di)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlinSerialization)
}

dependencies {
    commonMainImplementation(projects.feature.auth.domain)
    commonMainImplementation(projects.core.remote)
    commonMainImplementation(projects.core.config)
    commonMainImplementation(projects.core.data)
    commonMainImplementation(projects.core.mapping)
    commonMainImplementation(libs.kotlinx.coroutines.core)
    commonMainImplementation(libs.kotlinx.serialization.json)

    // Ktorfit — REST DataSource implementations are generated by its KSP processor.
    commonMainImplementation(libs.ktorfit.lib.light)
    commonMainImplementation(libs.ktorfit.annotations)

    add("kspCommonMainMetadata", projects.core.processor)
    add("kspCommonMainMetadata", libs.ktorfit.ksp)
}
