package com.domatapp.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Snackbar
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import com.domatapp.core.design.theme.DomatTheme
import com.domatapp.core.navigation.OnboardingGraph
import com.domatapp.core.navigation.gezginJson
import com.domatapp.core.navigation.gezginTopology
import com.domatapp.core.presentation.compose.LocalSnackbarHostState
import com.domatapp.feature.auth.presentation.navigation.authGraphEntries
import com.domatapp.feature.home.presentation.navigation.mainGraphEntries
import com.domatapp.feature.onboarding.presentation.navigation.onboardingGraphEntries
import dev.gezgin.core.compose.GezginDisplay
import dev.gezgin.core.compose.rememberNavigator

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            DomatTheme {
                DomatApp(onRootBack = { finish() })
            }
        }
    }
}

@Composable
fun DomatApp(onRootBack: () -> Unit) {
    val snackbarHostState = remember { SnackbarHostState() }

    // Replaces MainViewModel's hand-rolled back stack. `gezginTopology` and `gezginJson` are
    // generated by Gezgin into :core:navigation, next to the graph they describe; the navigator is
    // held in an Activity-scoped holder, so it survives configuration change, and its serialized
    // snapshot survives process death under `restoreKey`.
    val navigator = rememberNavigator(
        start = OnboardingGraph.OnboardingWelcomeRoute,
        topology = gezginTopology,
        json = gezginJson,
        restoreKey = "domat-root",
        onRootBack = onRootBack,
    )

    CompositionLocalProvider(LocalSnackbarHostState provides snackbarHostState) {
        Scaffold(
            snackbarHost = {
                SnackbarHost(hostState = snackbarHostState) { data ->
                    Snackbar(
                        snackbarData = data,
                        containerColor = MaterialTheme.colorScheme.errorContainer,
                        contentColor = MaterialTheme.colorScheme.onErrorContainer
                    )
                }
            }
        ) { innerPadding ->
            // The entries lambda is captured once, on first composition - every register call in
            // it must be unconditional.
            GezginDisplay(
                navigator = navigator,
                modifier = Modifier.padding(innerPadding),
                transitions = DomatNavTransitions,
            ) {
                onboardingGraphEntries()
                authGraphEntries()
                mainGraphEntries()
            }
        }
    }
}
