package com.domatapp.feature.auth.data.datasource

import com.domatapp.core.remote.annotations.Body
import com.domatapp.core.remote.annotations.DELETE
import com.domatapp.core.remote.annotations.GET
import com.domatapp.core.remote.annotations.Header
import com.domatapp.core.remote.annotations.POST
import com.domatapp.core.remote.annotations.RemoteDataSource
import com.domatapp.core.remote.annotations.Subscribe
import com.domatapp.feature.auth.data.dto.GoogleSignInRequest
import com.domatapp.feature.auth.data.dto.RemoteUserDto
import kotlinx.coroutines.flow.Flow

/**
 * Remote data source for authentication.
 * Implementation is automatically generated by KSP using RemoteApi.
 */
@RemoteDataSource
interface AuthRemoteDataSource {

    /**
     * Sign in with Google ID token.
     */
    @POST("auth/google")
    suspend fun signInWithGoogle(
        @Body request: GoogleSignInRequest
    ): RemoteUserDto

    /**
     * Retrieve current session.
     */
    @GET("auth/session")
    suspend fun getSession(
        @Header("Authorization") token: String
    ): RemoteUserDto

    /**
     * Logout current user.
     */
    @DELETE("auth/session")
    suspend fun logout(
        @Header("Authorization") token: String
    )

    @Subscribe("my/test/topic")
    suspend fun observeSession(
        token: String
    ): Flow<String>
}
