package com.domatapp.feature.auth.data.datasource

import com.domatapp.core.local.annotations.Clear
import com.domatapp.core.local.annotations.ClearAll
import com.domatapp.core.local.annotations.LocalDataSource
import com.domatapp.core.local.annotations.Retrieve
import com.domatapp.core.local.annotations.Save
import kotlinx.coroutines.flow.Flow

/**
 * Local data source for authentication.
 * Implementation will be automatically generated by KSP using KeyValueApi.
 */
@LocalDataSource(name = "auth")
interface AuthLocalDataSource {

    /**
     * Save the user session token.
     */
    @Save(KEY_TOKEN)
    suspend fun saveToken(token: String)

    /**
     * Retrieve the user session token.
     */
    @Retrieve(KEY_TOKEN)
    fun retrieveToken(): Flow<String?>

    /**
     * Clear the user session token.
     */
    @Clear(KEY_TOKEN)
    suspend fun clearToken()

    /**
     * Clear all auth related local data.
     */
    @ClearAll
    suspend fun clearAll()

    companion object {
        const val KEY_TOKEN = "user_token"
        const val STORE_NAME = "auth"
    }
}
