package com.domatapp.feature.auth.data.datasource

import com.domatapp.core.remote.annotations.*
import com.domatapp.feature.auth.data.dto.GoogleSignInRequest
import com.domatapp.feature.auth.data.dto.RemoteUserDto

/**
 * Remote data source for authentication.
 * Implementation is automatically generated by KSP using RemoteApi.
 */
@RemoteDataSource
interface AuthRemoteDataSource {

    /**
     * Sign in with Google ID token.
     */
    @POST("auth/google")
    suspend fun signInWithGoogle(
        @Body request: GoogleSignInRequest
    ): RemoteUserDto

    /**
     * Retrieve current session.
     */
    @GET("auth/session")
    suspend fun getSession(
        @Header("Authorization") token: String
    ): RemoteUserDto

    /**
     * Logout current user.
     */
    @DELETE("auth/session")
    suspend fun logout(
        @Header("Authorization") token: String
    )
}
