package com.domatapp.feature.auth.data.datasource

import com.domatapp.feature.auth.data.remote.AuthSessionRemoteModel
import com.domatapp.feature.auth.data.remote.GoogleSignInRemoteModel
import de.jensklingenberg.ktorfit.http.Body
import de.jensklingenberg.ktorfit.http.POST
import de.jensklingenberg.ktorfit.http.Query

/**
 * Remote data source for authentication via Supabase.
 * The implementation is generated by Ktorfit's KSP processor as the
 * `Ktorfit.createAuthRemoteSource()` extension function.
 *
 * Paths are relative to the Ktorfit base URL configured in `core:remote` (`provideKtorfit`).
 */
interface AuthRemoteSource {

    /**
     * Sign in with Google ID token via Supabase auth endpoint.
     */
    @POST("auth/v1/token")
    suspend fun signInWithIdToken(
        @Query("grant_type") grantType: String,
        @Body body: GoogleSignInRemoteModel
    ): AuthSessionRemoteModel

    /**
     * Logout current user.
     */
    @POST("auth/v1/logout")
    suspend fun logout()
}
