package com.domatapp.feature.auth.data.datasource

import com.domatapp.core.remote.annotations.GET
import com.domatapp.core.remote.annotations.Query
import com.domatapp.core.remote.annotations.RemoteDataSource
import com.domatapp.feature.auth.data.remote.UserProfileRemoteModel

/**
 * Remote data source for user profile operations via Supabase PostgREST.
 * Implementation is automatically generated by KSP.
 */
@RemoteDataSource
interface UserProfileRemoteDataSource {

    /**
     * Get user profile by ID.
     * Query format for Supabase PostgREST: userId = "eq.{userId}", select = "id"
     */
    @GET("rest/v1/profiles")
    suspend fun getProfile(
        @Query("id") userId: String,
        @Query("select") select: String
    ): List<UserProfileRemoteModel>
}
