package com.domatapp.feature.auth.data.datasource

import com.domatapp.feature.auth.data.remote.UserProfileRemoteModel
import de.jensklingenberg.ktorfit.http.GET
import de.jensklingenberg.ktorfit.http.Query

/**
 * Remote data source for user profile operations via Supabase PostgREST.
 * The implementation is generated by Ktorfit's KSP processor as the
 * `Ktorfit.createUserProfileRemoteSource()` extension function.
 */
interface UserProfileRemoteSource {

    /**
     * Get user profile by ID.
     * Query format for Supabase PostgREST: userId = "eq.{userId}", select = "id"
     */
    @GET("rest/v1/profiles")
    suspend fun getProfile(
        @Query("id") userId: String,
        @Query("select") select: String
    ): List<UserProfileRemoteModel>
}
