package com.domatapp.feature.auth.data.di

import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.Module

/**
 * Koin module for Auth Data layer.
 * Uses KSP to generate definitions via @ComponentScan.
 * AuthRemoteDataSourceImpl is automatically generated by KSP and registered as @Single.
 */
@Module
//@ComponentScan("com.domatapp.feature.auth.data")
class AuthDataModule