package com.domatapp.feature.auth.data.di

import com.domatapp.core.remote.rest.KtorRestClient
import com.domatapp.feature.auth.data.datasource.AuthRemoteDataSource
import com.domatapp.feature.auth.data.datasource.AuthRemoteDataSourceImpl
import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.Module
import org.koin.core.annotation.Single

/**
 * Koin module for Auth Data layer.
 * Uses KSP to generate definitions via @ComponentScan.
 * AuthRemoteDataSourceImpl is generated by KSP (core:processor) and manually provided here
 * because Koin KSP cannot discover @Single on classes generated by other processors.
 */
@Module
@ComponentScan("com.domatapp.feature.auth.data")
class AuthDataModule {

    @Single
    fun provideAuthRemoteDataSource(restClient: KtorRestClient): AuthRemoteDataSource =
        AuthRemoteDataSourceImpl(restClient)
}
