package com.domatapp.feature.auth.presentation.navigation

import com.domatapp.feature.auth.presentation.screen.location.provideLocationSelectionEntry
import com.domatapp.feature.auth.presentation.screen.login.provideLoginEntry
import dev.gezgin.core.compose.GezginEntryScope

/**
 * The feature's own entry bundle, handed to `GezginDisplay` by the host.
 *
 * `provideLoginEntry` / `provideLocationSelectionEntry` are generated by Gezgin into the package of
 * each `@Screen` composable, so they come from the `screen.login` / `screen.location` packages
 * rather than from here.
 */
fun GezginEntryScope.authGraphEntries() {
    provideLoginEntry()
    provideLocationSelectionEntry()
}
