package com.domatapp.feature.checkout.presentation.navigation

import com.domatapp.feature.checkout.presentation.screen.address.provideAddressEntry
import com.domatapp.feature.checkout.presentation.screen.confirmation.provideOrderConfirmationEntry
import com.domatapp.feature.checkout.presentation.screen.otp.provideOtpVerifyEntry
import com.domatapp.feature.checkout.presentation.screen.payment.providePaymentEntry
import com.domatapp.feature.checkout.presentation.screen.phone.providePhoneEntryEntry
import com.domatapp.feature.checkout.presentation.screen.windowclosed.provideWindowClosedEntry
import dev.gezgin.core.compose.GezginEntryScope

/**
 * The feature's entry bundle, handed to `GezginDisplay` by the host. Each `provide…Entry` is
 * generated by Gezgin into the package of its `@Screen` composable.
 */
fun GezginEntryScope.checkoutGraphEntries() {
    providePhoneEntryEntry()
    provideOtpVerifyEntry()
    provideAddressEntry()
    providePaymentEntry()
    provideOrderConfirmationEntry()
    provideWindowClosedEntry()
}
