package com.domatapp.feature.checkout.presentation.navigation

import com.domatapp.feature.checkout.presentation.screen.payment.providePaymentEntry
import dev.gezgin.core.compose.GezginEntryScope

/**
 * The feature's entry bundle, handed to `GezginDisplay` by the host. `providePaymentEntry` is
 * generated by Gezgin into the package of the `@Screen` composable.
 */
fun GezginEntryScope.checkoutGraphEntries() {
    providePaymentEntry()
}
